routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('clube', 'ClubeController');

Route::resource('socio', 'SocioController');

app/Clube.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clube extends Model
{
    public $fillable = ['name'];
}

app/Socio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Socio extends Model
{
    public $fillable = ['name', 'clube_id'];

    public function clube(){
        return $this->belongsTo(Clube::class);
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClubeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Clube;

class ClubeController extends Controller
{

    private $clube;
    
    public function __construct(Clube $clube)
    {
        $this->middleware('auth');
        $this->clube = $clube;
    }

    
    public function index()
    {

        return view('clube.index', [
            'clubes' => $this->clube->all()
        ]);
    }

    
    public function create()
    {
        return view('clube.create');
    }

    
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|max:255',
        ]);

        $this->clube->create($request->all());

        return redirect()->route('clube.index');
    }


    public function edit(Clube $clube)
    {
        return view('clube.edit', [
            'clube' => $clube
        ]);
    }

    public function update(Clube $clube, Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
        ]);

        $clube->name = $request->all()['name'];
        $clube->save();

        return redirect()->route('clube.index');
    }
    
    public function destroy(Clube $clube)
    {

        $clube->delete();

        return redirect()->route('clube.index');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SocioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Clube;
use App\Socio;

class SocioController extends Controller
{
    
    private $clube;
    private $socio;

    public function __construct(Clube $clube, Socio $socio)
    {
        $this->middleware('auth');

        $this->socio = $socio;
        $this->clube = $clube;
    }

    
    public function index()
    {
        return view('socio.index', [
            'socios' => $this->socio->all()
        ]);
    }

    
    public function create()
    {
        return view('socio.create', [
            'clubes' => $this->clube->all()
        ]);
    }

    
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'clube_id' => 'max:255|integer',
        ]);

        $this->socio->create($request->all());

        return redirect()->route('socio.index');
    }
    
        
    public function edit(Socio $socio)
    {
        return view('socio.edit', [
            'clubes' => $this->clube->all(),
            'socio' => $socio
        ]);
    }

    
    public function update(Socio $socio, Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255',
            'clube_id' => 'max:255|integer',
        ]);


        $socio->name = $request->all()['name'];
        $socio->clube_id = ($request->all()['clube_id'] ?: "");
        $socio->save();

        return redirect()->route('socio.index');
    }
    
    public function destroy(Socio $socio)
    {

        $socio->delete();

        return redirect()->route('socio.index');
    }
}

resources/views/clube/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Cadastro de Clube</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('clube.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Cadstrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clube/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edição de Socio</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('clube.update', $clube->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ (old('name') ?: $clube->name) }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Editar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clube/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Clubes
                    <ul class="nav navbar-nav navbar-right" style='margin-right: 20px;'>
                        <li><a href='{{route("clube.create")}}'>Cadastrar Clubes</a></li>
                    </ul>
                </div>

                <div class="panel-body">
                    <table>
                        <tr>
                            <th>Nome</th>
                            <th colspan='2'>Ações</th>
                        </tr>
                        @if(count($clubes) > 0)
                            @foreach($clubes as $clube)
                                <tr>
                                    <td>{{$clube['name']}}</td>
                                    <td><a href='{{route("clube.edit", $clube["id"])}}'>Editar</a> | <form style='float: right' action='{{route("clube.destroy", $clube["id"])}}' method='POST'>{{ csrf_field() }}{{ method_field('DELETE') }}<input type='submit' value='Deletar' /></form></td>
                                    
                                </tr>
                            @endforeach
                        @endif

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href='{{route("clube.index")}}'>Clube</a></li>
                        <li><a href='{{route("socio.index")}}'>Socios</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/socio/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Cadastro de Socio</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('socio.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        @if(count($clubes) > 0)
                            <div class="form-group{{ $errors->has('clube_id') ? ' has-error' : '' }}">
                                <label for="clube_id" class="col-md-4 control-label">Clube</label>

                                <div class="col-md-6">

                                    <select id="clube_id" type="text" class="form-control" name="clube_id" >
                                        <option value=''>Selecione um clube</option>
                                        @foreach($clubes as $clube)
                                            <option value='{{$clube["id"]}}' {{(old('clube_id') == $clube["id"] ? 'selected' : '')}}>{{$clube["name"]}}</option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('clube_id'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('clube_id') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        @endif

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Cadastrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/socio/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Cadastro de Socio</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('socio.update', $socio->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ (old('name') ?: $socio->name) }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        @if(count($clubes) > 0)
                            <div class="form-group{{ $errors->has('clube_id') ? ' has-error' : '' }}">
                                <label for="clube_id" class="col-md-4 control-label">Clube</label>

                                <div class="col-md-6">

                                    <select id="clube_id" type="text" class="form-control" name="clube_id" >
                                        <option value=''>Selecione um clube</option>
                                        @foreach($clubes as $clube)
                                            <option value='{{$clube["id"]}}' {{(old('clube_id') == $clube["id"] ? 'selected' : ($clube->id == $socio->clube->id ? 'selected' : ''))}}>{{$clube["name"]}}</option>
                                        @endforeach
                                    </select>

                                    @if ($errors->has('clube_id'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('clube_id') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        @endif

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Editar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/socio/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                    <ul class="nav navbar-nav navbar-right" style='margin-right: 20px;'>
                        <li><a href='{{route("socio.create")}}'>Cadastrar Socios</a></li>
                    </ul>
                </div>

                <div class="panel-body">
                    <table>
                        <tr>
                            <th>Nome</th>
                            <th>Clube</th>
                            <th colspan='2'>Ações</th>
                        </tr>
                        @if(count($socios) > 0)
                            @foreach($socios as $socio)
                                <tr>
                                    <td>{{$socio['name']}} - </td>
                                    <td>{{$socio->clube->name}} - </td>
                                    <td><a href='{{route("socio.edit", $socio["id"])}}'>Editar</a> | <form style='float: right' action='{{route("socio.destroy", $socio["id"])}}' method='POST'>{{ csrf_field() }}{{ method_field('DELETE') }}<input type='submit' value='Deletar' /></form></td>
                                    
                                </tr>
                            @endforeach
                        @endif

                    </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection